// flow-typed signature: 83402b6bf358de8494cf60c09a01e047
// flow-typed version: <<STUB>>/react-router-test-context_v^0.1.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-test-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-test-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-router-test-context/index' {
  declare module.exports: $Exports<'react-router-test-context'>;
}
declare module 'react-router-test-context/index.js' {
  declare module.exports: $Exports<'react-router-test-context'>;
}
